### ISSUE TITLE
Where is aws servicecatalog list-products?

### ISSUE THREAD

**Issue by john-aws** [aws/aws-sdk#147]
I'm raising this issue to help future readers work out how to get a list of Service Catalog products from the awscli.

There are closely-related commands:

- aws servicecatalog list-portfolios
- aws servicecatalog list-portfolios-for-product

But there is no:

- aws servicecatalog list-products

Instead, it looks like you use:

- aws servicecatalog search-products-as-admin

**Comment by shdobxr** [comment]
Also FWIW, I also naturally performed list-<tab> and didn't find what I wanted.
`aws servicecatalog search-provisioned-products` search doesn't make sense as it actually dumps a list.

**Comment by tim-finnigan** [comment]
It is confusing that the API pattern is `search-*` rather than `list-*` or `describe-*` as most other services use. But since it was released this way the API likely won't change in order to maintain backwards compatibility. And in the Developer Guide there is a now an example workflow that highlights using the `SearchProducts` API. So since that was completed I will go ahead and close this issue. If there's anything further you'd like to discuss related to this please let us know here or consider reaching out to [AWS Support](https://aws.amazon.com/contact-us/). Thanks!

**Comment by fitz-res** [comment]
This is a very confusing experience.
Is there no way to list products owned by my account or products associated with a portfolio?
