### ISSUE TITLE
AmazonMQ Configuration for RabbitMQ

### ISSUE THREAD

**Issue by Richard-Payne** [aws/aws-sdk#148]
**Is your feature request related to a problem? Please describe.**
We configure infrastructure automatically, in our case using Terraform.  When configuring a RabbitMQ broker there is no support for configuring vhosts, exchanges and permissions through the AWS api.  This means that there is no way to automatically configure the broker using a Infrastructure as Code paradigm.  

**Describe the solution you'd like**
Additional aws mq functions for configured vhosts and permissions on RabbitMQ brokers.
For example:

aws mq configure-rabbit-broker create-vhost --broker-id b-4340958340943 ---vhost /myvhost
aws mq configure-rabbit-broker delete-vhost --broker-id b-4340958340943 ---vhost /myvhost

aws mq configure-rabbit-broker create-exchange --broker-id b-4340958340943 ---vhost /myvhost --exchange topic1
aws mq configure-rabbit-broker delete-exchange --broker-id b-4340958340943 ---vhost /myvhost --exchange topic1

aws mq configure-rabbit-broker create-vhost-permissions --broker-id b-4340958340943 ---vhost /myvhost --user user1 --configure .* --read .* --write .*
aws mq configure-rabbit-broker update-vhost-permissions --broker-id b-4340958340943 ---vhost /myvhost --user user1 --configure .* --read .* --write .*
aws mq configure-rabbit-broker delete-vhost-permissions --broker-id b-4340958340943 ---vhost /myvhost --user user1

aws mq configure-rabbit-broker create-exchange-permissions --broker-id b-4340958340943 ---exchange topic1 --user user1 --configure .* --read .* --write .*
aws mq configure-rabbit-broker update-exchange-permissions --broker-id b-4340958340943 ---exchange topic1 --user user1 --configure .* --read .* --write .*
aws mq configure-rabbit-broker delete-exchange-permissions --broker-id b-4340958340943 ---exchange topic1 --user user1

**Describe alternatives you've considered**
The only alternative I can see is manual configuration which is less than ideal in an IAC world.

**Comment by tim-finnigan** [comment]
A member of the service team said that since Amazon MQ for RabbitMQ brokers expose the RabbitMQ management API, it is possible to use https://github.com/hashicorp/terraform-provider-rabbitmq. There is also the approach mentioned in [this earlier comment](https://github.com/aws/aws-sdk/issues/148#issuecomment-743094826) above. I don't think the specific APIs requested are planned but I hope that addresses your use case. Please let us know if you had any additional feedback to share or consider reaching out to [AWS Support](https://aws.amazon.com/contact-us/).
