### ISSUE TITLE
`DescribeTrainingJob` returns `ValidationException` instead of `ResourceNotFoundException` for non-existent resource

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#165]
Origin: https://github.com/boto/boto3/issues/2808, Requester: @haandol  

**Describe the bug**
> describe_training_job method occurs ValidationException instead of ResourceNotFound for not existing resource.

**Steps to reproduce**
> tested on boto3==1.17.43, botocore==1.20.43

```
import boto3                                                                       
import botocore                                                                    
                                                                                   
client = boto3.client('sagemaker')                                                 
                                                                                   
try:                                                                               
    print(client.describe_training_job(TrainingJobName='not-existing-training-job-name'))                
except client.exceptions.ResourceNotFound:                                         
    print('caught')                                                                
except botocore.exceptions.ClientError as error:                                   
    if error.response['Error']['Code'] == 'ResourceNotFound':                      
        print('caught inner')                                                      
    else:                                                                          
        print(error.response)                                                      
        print('common') 
```
**Expected behavior**
> above code should raise ResourceNotFound error and print caught
but it raises ValidationException and prints common

**Service team request:** V341946505

**Comment by tim-finnigan** [comment]
The service team is continuing to track this issue in their backlog. As mentioned in the original issue, this would likely be a documentation change rather than an API behavior change, because this is technically old behavior that would be backwards-incompatible if changed. For any additional documentation feedback you can use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=SageMaker&topic_url=https://docs.aws.amazon.com/en_us/sagemaker/latest/APIReference/API_DescribeTrainingJob.html) link at the bottom of API documentation pages like [DescribeTrainingJob](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeTrainingJob.html).
