### ISSUE TITLE
 `RunJobFlow` fails when `OnDemandPrice` is provided as an `InstanceGroups`, `BidPrice` value

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#167]
Origin: https://github.com/boto/boto3/issues/2866, Requester: @shanfadnis 

**What issue did you see ?**

I am trying to submit a job flow on EMR to start a cluster. I want to set bid price as "OnDemandPrice" instead of USD amount as per the documentation here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.run_job_flow

However, when I invoke run_job_flow() I get the following exception:

`botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the RunJobFlow operation: The bid price is invalid. Revise the configuration and resubmit.`

My configuration for the instanceGroups looks like this:

```
"InstanceGroups": [
            {
                "InstanceRole": "MASTER",
                "Market": "SPOT",
                "InstanceType": "r5d.16xlarge",
                "BidPrice": "OnDemandPrice",
                "InstanceCount": 1
            },
            {
                "InstanceRole": "CORE",
                "Market": "SPOT",
                "InstanceType": "r5d.16xlarge",
                "BidPrice": "OnDemandPrice",
                "InstanceCount": 5
            }
        ]
```

**Service team request:**P67036172

**Comment by tim-finnigan** [comment]
Checking in – the EMR docs team is still tracking this issue in their backlog. For future reference we recommend using the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=EMR&topic_url=http://docs.aws.amazon.com/en_us/emr/latest/APIReference/API_RunJobFlow.html) links at the bottom of API documentation pages like https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html in order to provide feedback directly to the appropriate team.
