### ISSUE TITLE
Include an option for deploy a Sagemaker domain with SSO group information 

### ISSUE THREAD

**Issue by cabral1888** [aws/aws-sdk#189]
Today, I have a Sagemaker Domain integrated with SSO. This is working fine, I can add users or groups any time I want and give them access to Sagemaker Studio with no need to login into my AWS account. My problem is that after deploying my Sagemaker Domain, I need to manually attach the SSO Group to it in the console, in order to allow the users from that group to access Sagemaker Studio. I can't write a 100% automatized deploy process because the group information needs to be manually included in the console. I plan to have tens of groups, so that will be terrible in long term.

The parameters described in the aws-cli command `aws sagemaker create-domain` doesn't include anything related to deploying an Domain with an AWS SSO group configured already. Are you planning to add this feature in the next months? Is that in the AWS Roadmap?

**Comment by tim-finnigan** [comment]
P59995196

**Comment by CandiedCode** [comment]
I am interested in this feature as well.  My setup for Sagemaker is IAC but since I can't find SDK support for using SSO Groups, the only way to configure this (as shown below), is either manually or to not use groups and add each individual SSO user.

<img width="1036" alt="Screen Shot 2022-03-20 at 2 12 10 PM" src="https://user-images.githubusercontent.com/8380706/159178808-983d26bb-d9a4-4c7e-8ee1-325deb548899.png">

**Comment by tim-finnigan** [comment]
Thanks for sharing your use cases here. I heard back from a member of the Identity Center team (which is the successor to SSO) and they have added this feature request to their list for consideration. Please feel free to check back in here for updates in the future or reach out to [AWS Support](https://aws.amazon.com/contact-us/).
