### ISSUE TITLE
add "arn" as an accessible attribute to s3.Bucket 

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#197]
Original issue: https://github.com/boto/boto3/issues/3176

**Comment by tim-finnigan** [comment]
P60792445

**Comment by tim-finnigan** [comment]
A member of the S3 team told me that this feature request was added to their backlog for tracking. It will be evaluated and prioritized for the S3 roadmap alongside other feature enhancement requests. I'm going to go ahead and close this issue but if you want an update please let me know and I can reach out to the S3 team to see what the status of this feature request is.

**Comment by cmaggiulli** [comment]
Honestly it's frustrating that this doesn't exist.  I feel like this is something an intern could do and it's frustrating because I have code that I'm trying to generalize and I need several special cases to convert custom scheme url's to ARN's ( which itself doesnt exist as a helper method ).  It's not difficult to implement but it liters my code with logical branching that is otherwise unnecessary
