### ISSUE TITLE
Replace a JSON trust relationship document with SDKs API.

### ISSUE THREAD

**Issue by Oleh-Stefanovych** [aws/aws-sdk#244]
## Describe the Feature

I suggest getting rid of the JSON  trust relationship document.
## Is your Feature Request related to a problem?

I'm always frustrated when I should provide JSON assume role policy document to create a role or other related request, e.g.:
```java
    private static final String TRUST_RELATIONSHIP = "{\n" +
        "  \"Version\": \"2020-01-01\",\n" +
        "  \"Statement\": [\n" +
        "    {\n" +
        "      \"Effect\": \"Allow\",\n" +
        "      \"Principal\": {\n" +
        "        \"Service\": \"lambda.amazonaws.com\"\n" +
        "      },\n" +
        "      \"Action\": \"sts:AssumeRole\"\n" +
        "    }\n" +
        "  ]\n" +
        "}";

    // ...

    CreateRoleRequest createRoleRequest = CreateRoleRequest.builder()
        .roleName("foo-bar")
        .assumeRolePolicyDocument(TRUST_RELATIONSHIP)
        .build();

    iamClient.createRole(createRoleRequest);
```
## Proposed Solution

```java
         TrustRelationshipStatement relationshipStatement = TrustRelationshipStatement.builder()
            .effect(Effect.ALLOW)
            .action(Action.ASSUME_ROLE)
            .principal(ServicePrincipal.AWS_LAMBDA)
            .build();
        
        List<TrustRelationshipStatement> relationshipStatements = new ArrayList<>();
        relationshipStatements.add(relationshipStatement);
        
        TrustRelationship trustRelationship = TrustRelationship.builder()
            .version("2020-01-01")
            .statements(relationshipStatements)
            .build();

        CreateRoleRequest createRoleRequest = CreateRoleRequest.builder()
            .roleName("foo-bar")
            .assumeRolePolicyDocument(trustRelationship)
            .build();

        iamClient.createRole(createRoleRequest);
```

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: 2.10.66
* JDK version used: 11

**Comment by debora-ito** [comment]
@Oleh-Stefanovych The IAM Policy Builder is now available in the Java SDK 2.x -
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/policybuilder/iam/IamPolicy.html

The IAM Policy Builder is a client-side library that facilitates the construction of IAM policies and easily converts to JSON. We have some code examples in the Java SDK 2.x Developer Guide -
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/feature-iam-policy-builder.html

Since your use-case was for Java SDK 2.x originally, I'll mark this to auto-close soon. 

If anyone else is interested in seeing this library in other AWS SDKs, please open a new Github issue and let us know which SDK you're using.
