### ISSUE TITLE
AWS SSO: Support listing applications and assigned users / groups through SDKs and CLI

### ISSUE THREAD

**Issue by erosen03** [aws/aws-sdk#290]
It appears that listing AWS SSO applications and assigned users / groups through SDKs / CLI / PowerShell is not supported. Could this please be added to SDKs / CLI / PowerShell. It is very important for us to be able to programmatically retrieve the data in order to comply with organizational risk management policies related to user and group permissions in AWS. Organizational audit for user and group permissions in AWS is reported to the board of directors on the organization's financial  statement.

**Comment by tim-finnigan** [comment]
Thanks @erosen03 for the feature request. However it looks like this overlaps with existing issues https://github.com/aws/aws-sdk/issues/109 and https://github.com/aws/aws-sdk/issues/144. I just reached out to the SSO team for an update and we will update those as soon as we hear back. If there are any distinctions that you want to highlight please let us know, otherwise I will go ahead and close this in order to consolidate the tracking issues.

**Comment by erosen03** [comment]
Hi @tim-finnigan, I agree that this issue is in the same category as #144, but this issue is a bit different. #144 talks about group membership. Rather than group membership, this issue is more about user and group assignments to SSO applications. The API request I'm making is akin to creating a Get-SSOADMN**Applicationt**AssignmentList, like the Get-SSOADMN**Account**AssignmentList already in the API.

**Comment by tim-finnigan** [comment]
Thanks @erosen03 for clarifying that. In this case it seems that https://github.com/aws/aws-sdk/issues/109 is the more similar issue to this one. Although the issues in this repository involve APIs used by SDKs and it looks like you maybe be using Powershell. But I can pass along the distinctions you described in your request to the SSO team.
