### ISSUE TITLE
How to get the usage quota of vpc endpoint ?

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk#34]
Hello,

I could not figure out the right command to get the usage of the vpc endpoint(interface endpoint.)

The below command just gives the default quota.

```
 aws service-quotas get-service-quota --service-code 'vpc' --quota-code 'L-F678F1CE'
```

Can someone help?

BRs, Gowrisankar

**Comment by tim-finnigan** [comment]
P51136408

**Comment by tim-finnigan** [comment]
Hi @gowrisankar22, thanks for your patience. Just to clarify, are you trying to see your VPCs per Region usage relative to the quota?

In the [CLI documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/get-service-quota.html) for `get-service-quota` the example output does not show specific usage, although `UsageMetric` is shown. Is that what you are referring to?

You can check VPCs per Region usage from the TrustedAdvisor service (TrustedAdvisor → Service Limits → VPC). If you would like to monitor this usage, you can also create a CloudWatch alarm as described here: https://aws.amazon.com/blogs/mt/monitoring-service-limits-with-trusted-advisor-and-amazon-cloudwatch/

**Comment by tim-finnigan** [comment]
Hi @gowrisankar22 since it's been over a week and we haven't heard back, I am going to close this issue. As far as I can tell the `get-service-quota` command is working as intended. 

Please note how you can check VPCs per Region usage as mentioned above. And if you just want to see how many VPCs you have, you can run the command `aws ec2 describe-vpcs` as documented here: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-vpcs.html
