### ISSUE TITLE
Incorrect data validation is applied to `bot-version` in `lex2v-models` `describe-bot-version`

### ISSUE THREAD

**Issue by convexset** [aws/aws-sdk#342]
### Describe the bug

Incorrect data validation is applied to `bot-version` in `lex2v-models` `describe-bot-version`

### Expected Behavior

Bot version information to be returned for valid `bot-id` and `bot-version`.

### Current Behavior

There seems to be incorrect data validation:

```
$ aws lexv2-models describe-bot-version --bot-id BOTID123 --bot-version DRAFT

An error occurred (ValidationException) when calling the DescribeBotVersion operation:
1 validation error detected: Value 'DRAFT' at 'botVersion' failed to satisfy constraint:
Member must satisfy regular expression pattern: ^[0-9]+$
```

### Reproduction Steps

Create any Lex v2 bot, and do something like:

```
$ aws lexv2-models describe-bot-version --bot-id BOTID123 --bot-version DRAFT

An error occurred (ValidationException) when calling the DescribeBotVersion operation:
1 validation error detected: Value 'DRAFT' at 'botVersion' failed to satisfy constraint:
Member must satisfy regular expression pattern: ^[0-9]+$
```

### Possible Solution

Fix the data validation regex.

### CLI version used

aws-cli/2.4.19 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Darwin/21.6.0 exe/x86_64

**Comment by tim-finnigan** [comment]
P71003536

**Comment by tim-finnigan** [comment]
We heard back from the Lex team who said this is intended and by design. The [DescribeBotVersion API](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_DescribeBotVersion.html) is specifically designed to get information around a numerical (immutable) version. To get information around a DRAFT (mutable) version we have the [DescribeBot API](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_DescribeBot.html) which by default is querying the draft version. I hope that helps clear things up - please let us know if you had any other questions.
