### ISSUE TITLE
AWS LEX v2 Runtime URL is not updating with new bot id

### ISSUE THREAD

**Issue by vinayburam** [aws/aws-sdk#347]
Hi Team,
I am facing one strange issue, I am trying to use existing lex web UI , SO I have Modified below config
1) lex-web-ui-loader-config.json -- > changed with new bot ID, Alias ID and updated the file in s3 bucket
2)MOdified the existing IAM role , added region, account, bot id and alias ID , crossed checked this with cognito id

but still Runtimeurl is showing the previous config.

**Comment by bhoradc** [comment]
Hi @vinayburam,

Good Afternoon, since this issue was reported long time back, I would like to know if you still see this problem.
 
If yes, to help us troubleshoot the issue with your Lex web UI not updating, could you please clarify whether you're using any AWS SDK and/or AWS CLI to interact with Amazon Lex?

Also, if you are able to reliably replicate this issue, kindly provide more details on the steps to reproduce it. This will assist us to troubleshoot the issue effectively.

Regards, 
Chaitanya
