### ISSUE TITLE
Create aws-sdk-v repository

### ISSUE THREAD

**Issue by ulises-jeremias** [aws/aws-sdk#407]
### Describe the feature

Vlang is a programming language which has become very popular in recent years. It's trending on github trends and has a really big community. It is currently in the process of enlarging its ecosystem for various purposes and we are eager to provide cloud computing solutions as part of it. This is why we would like to collaborate in the development of an SDK for AWS in V.

### Use Case

Someone from the community created this [vlang aws lambda](https://github.com/aheissenberger/vlang-aws-lambda) example some time ago and it was needed to define all the types from scratch, but it was possible to create a custom runtime for V.
With this feature request we want to make it easier for future Vlang developers to create their apps and host them in aws using V.

### Proposed Solution

As a member of the Vlang Core Team I offer myself to start the development of this solution and coordinate efforts and people to make this possible. Given my position as a member of the V team, I am a good point of contact, and given my experience working with AWS and the AWS SDK, I think I can carry forward the development of the first sdk for V. At the same time, I can be the point of contact for any AWS member who wants to follow up on this development.

Something I could do is a first implementation in a repo of mine to show how this could be used, but I would love if this repository could be part of the AWS github organization as it would be much easier to keep it up to date.

The idea would be to use the sdk in Go as a reference for the implementation of the sdk in V, since Go and V are very similar, and at the same time V has a tool under development to migrate code from Go to V

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

latest

### Environment details (OS name and version, etc.)

-

**Comment by kellertk** [comment]
Hi there! We don't have any short term plans to develop an AWS SDK for V lang. In general, repositories that are within the various Amazon orgs on GitHub, AWS included, are owned and developed by Amazon employees. By ownership I mean license and copyright, and developed by I mean the project maintainers and stewards. There might be specific exceptions out there, but AWS SDKs are developed that way; we won't create an aws-sdk-v repository unless we plan to release a V SDK from AWS.

That doesn't mean you shouldn't move forward with developing your own, though - some have taken that approach in the past: [Rusoto](https://github.com/rusoto/rusoto) is one example, but there are [others](https://github.com/sdogruyol/aws), and of course boto was originally developed as a non-AWS project. Building an AWS SDK is somewhat complicated, as not all of our standard paradigms are documented publicly, and large parts of the code are generated from service models. We strive for consistency in behavior across SDKs for many things like configuration and authentication, and those are complex problems that even internally we're trying to constantly improve. Newer AWS SDKs use [Smithy codegen](https://smithy.io/2.0/implementations.html#aws-specific), but even with Smithy some amount of manual work is required to create a functional client SDK. Some of this might be easier if you're able to migrate Go code, as the Go v2 SDK is built with Smithy, which right now is in the future plan for all new versions of the AWS SDKs.

Small housekeeping note: Since this isn't specific to the AWS CLI, I've transferred this issue to a more appropriate general repository.

**Comment by ylluminate** [comment]
@kellertk you may be interested to know that V is very closely modeled after Go, so a conversion of Go code is relatively straightforward in many regards - so that seems a good and solid target that could facilitate AWS participation / input since you have Go already under your, proverbial, belt.

**Comment by kellertk** [comment]
You're free to use whatever license you'd like for your project. Amazon SDKs are typically released under Apache-2.0.
