### ISSUE TITLE
Add AutoScaling waiter models

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#419]
Original issue: https://github.com/boto/boto3/issues/318

**Comment by tim-finnigan** [comment]
P75946755

**Comment by tim-finnigan** [comment]
We heard back from the AutoScaling team who created a backlog item for this feature request. We can't guarantee if or when this would be implemented but feel free to check back here for updates or by reaching out through [AWS Support](https://aws.amazon.com/contact-us/).

**Comment by shearn89** [comment]
18+ months on, and closing in on 9 years since [this request](https://github.com/boto/boto3/issues/318) was raised...

I can see `get_waiter` in the boto3 docs for AutoScaling - but no `waiters` section that lists any waiters. Any updates on this, or do we still have to do a `describe` in a for loop?

**Comment by cmt-jbrooks** [comment]
I have the same question. I was looking forward to using a waiter to simplify my work and provide some consistency around polling. I've reached out.
