### ISSUE TITLE
Remove Use of Non-Inclusive Language

### ISSUE THREAD

**Issue by belugabehr** [aws/aws-sdk#440]
### Describe the feature

Remove use of non-inclusive terms such as "black" and "white" list and instead prefer "deny" and "allow" list.

### Use Case

https://github.com/aws/aws-sdk-java-v2/blob/d139aed3c874b7503e378828e309514a5ef8b008/services/medialive/src/main/resources/codegen-resources/service-2.json#L5081-L5085

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2

### JDK version used

JDK 11

### Operating System and version

Linux

**Comment by yasminetalby** [comment]
D68040968

**Comment by yasminetalby** [comment]
The AWS Elemental Service team has decided to not implement this feature-request. Here is their statement regarding this request: 

"The use of whitelist in the MediaLive API predates AWS's Non Inclusive Language policy. We investigated making a breaking API change to move these older APIs to use allowlist instead of whitelist, but after consulting with our customers we decided to not make a breaking API change due to the wide-scale customer impact of making the change."

I will close this feature-request to reflect their decision.

Thank you very much for your submission and feedback. We really appreciate your time and contribution.

Sincerely,

Yasmine
