### ISSUE TITLE
IAM fuctions missing name path parameter

### ISSUE THREAD

**Issue by cp10000** [aws/aws-sdk#450]
### Describe the bug

Several aws cli IAM functions, like put-policy and others, are missing the usual "path" parameter for policy name, role name, group name, ....etc.   A complete review to correct this is required.   Note that some functions like create-policy or create-role already have the path parameter.   But it's not consistent across all IAM functions and it should be.

### Expected Behavior

All aws cli IAM functions that pass policy name or/and role name and/or group name should have a corresponding "path" parameter.   It's essential for proper use of IAM.

### Current Behavior

Function aws iam put-policy (and several other functions) is missing the "path" parameter.

### Reproduction Steps

aws iam put-policy help

### CLI version used

2.9.12

### Environment details (OS name and version, etc.)

ubuntu 18.04

**Comment by tim-finnigan** [comment]
Checking in again — if functionality is supported in Boto3 then it should generally also work with the CLI, as both the AWS CLI and Boto3 use the same models in [Botocore](https://github.com/boto/botocore). We haven't received any more details or customer reports of the issue here. For any future investigations please clarify which API(s) you are referring to (https://docs.aws.amazon.com/IAM/latest/APIReference/API_Operations.html) and how you are blocked with the existing behavior.
