### ISSUE TITLE
ECS Client ListConainterInstances example documentation is incorrect

### ISSUE THREAD

**Issue by alextwoods** [aws/aws-sdk#466]
The ECS container instance ARNs returned by `ListContainerInstances` include the cluster name in tail end of the ARN, after the string "container-instance" and before the container instance ID itself. Since you need just the container instance ID in calling methods like `UpdateContainerInstanceState`, knowing the proper format for value returned here is important.

The examples contain arns like `arn:aws:ecs:us-east-1:<aws_account_id>:container-instance/f6bbb147-5370-4ace-8c73-c7181ded911f` but *should* have: `arn:aws:ecs:us-east-1:<aws_account_id>:container-instance/default/f6bbb147-5370-4ace-8c73-c7181ded911f`.

See: https://github.com/aws/aws-sdk-ruby/pull/2819

**Comment by ashishdhingra** [comment]
This appears to be fixed in Ruby SDK V3 documentation [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#list_container_instances-instance_method). However, the example is incorrect in ECS service API [ListContainerInstances](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListContainerInstances.html) documentation.

**Comment by ashishdhingra** [comment]
P125686798

**Comment by ashishdhingra** [comment]
Opened ticket with service team.

**Comment by ashishdhingra** [comment]
P125714130
(ticket created for fix by docs team)

**Comment by ashishdhingra** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListContainerInstances.html is also fixed.
