### ISSUE TITLE
Directory named `META-INF` cannot be uploaded to an S3 bucket

### ISSUE THREAD

**Issue by kota65535** [aws/aws-sdk#482]
### Describe the bug

A directory named `META-INF` cannot be uploaded to an S3 bucket.

```
$ tree
.
└── META-INF
    └── MANIFEST.MF

$ aws s3 cp . s3://bucket-561678142736 --recursive
upload failed: META-INF/MANIFEST.MF to s3://bucket-561678142736/META-INF/MANIFEST.MF An error occurred (404) when calling the PutObject operation: Not Found
```

This S3 bucket has been created from a web console with default settings. I've tried some other buckets but the results were the same.

On the other hand, `META-INF` directory in another directory can be uploaded successfully.

```
$ tree
.
├── META-INF
│   └── MANIFEST.MF
└── bb
    └── META-INF
        └── MANIFEST.MF

$ aws s3 cp . s3://bucket-561678142736 --recursive
upload failed: META-INF/MANIFEST.MF to s3://bucket-561678142736/META-INF/MANIFEST.MF An error occurred (404) when calling the PutObject operation: Not Found
upload: bb/META-INF/MANIFEST.MF to s3://bucket-561678142736/bb/META-INF/MANIFEST.MF
```

### Expected Behavior

`META-INF` directory should be uploaded to an S3 bucket successfully.

### Current Behavior

See description

### Reproduction Steps

See description

### CLI version used

aws-cli/2.10.1 Python/3.11.2 Darwin/21.4.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Monterey 12.3.1

**Comment by kota65535** [comment]
@tim-finnigan Thank you for transferring this issue to the appropriate repository.

> Are you able to upload the directory via the console?

No, I also could not upload `META-INF` directory via the console due to Network Error.

**Comment by tim-finnigan** [comment]
Ok thanks for checking that. I escalated this to the S3 team so they are now aware of the issue. I don't know if there are plans to support adding `META-INF` at the root, possibly because that could interfere with the bucket configurations. But they are considering updating their documentation to call out this edge case. And the recommended workaround is to use a nested directory as you originally mentioned doing. Thanks again for bringing this to our attention.
