### ISSUE TITLE
A function called waitUntilFunctionDeployed for Cloudfront

### ISSUE THREAD

**Issue by cihad** [aws/aws-sdk#484]
### Describe the feature

It's better an existing function `waitUntilFunctionDeployed` like [waitUntilDistributionDeployed](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudfront/globals.html#waituntildistributiondeployed)

### Use Case

I'm doing some S3 bucket and directory redirects with the Cloudfront Viewer Request Function. I replace the function content with `UpdateFunctionCommand` and `PublishFunctionCommand` and publish it. Great! When he/she goes to the address given to the user without knowing whether the function is deployed or not, he/she encounters an error. It would be nice to tell the user to wait.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.276.0

### Environment details (OS name and version, etc.)

Nodejs

**Comment by cihad** [comment]
Thank you @RanVaknin,

How can I follow this feature request?

**Comment by RanVaknin** [comment]
Hi @cihad ,

Its an internal FR so theres no way for you to know unless we update you here on the thread. 

To be completely transparent, this might take a while, service teams usually have their roadmap for the next few months. 
Im hopeful that since this is something fairly easy it will get addressed sooner, but I even we on the SDK team don't have visibility to the predicted timeline of something like this.

Keep an eye on this thread for updates 👍 
Thanks for your patience, 
Ran~

**Comment by RanVaknin** [comment]
The service team has closed the feature request.
You are welcome to open an additional support ticket via the AWS console and be asked to get routed to the Cloudfront service team. You can reference the previous ticket `P82654047`.

Sorry for the inconvenience. 
Thanks,
Ran~
