### ISSUE TITLE
Add Paginator for ListHostedZonesByName

### ISSUE THREAD

**Issue by carvantes** [aws/aws-sdk#487]
### Describe the feature

Add Paginator for `ListHostedZonesByName`

Is there a reason why there is a [paginateListHostedZones](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-route-53/globals.html#paginatelisthostedzones) but not a `paginateListHostedZonesByName`?

Those 2 are distinct APIs and both support pagination:
- [ListHostedZones](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListHostedZones.html)
- [ListHostedZonesByName](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListHostedZonesByName.html)

### Use Case

I'm always frustrated when an API supports pagination but the sdk has no Paginator

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

macOs, but it is irrelevant

**Comment by RanVaknin** [comment]
Hi @carvantes 
I let the R53  team know and they've placed this on their backlog. We can't share specific timelines on when this might be implemented. Since this is not actionable by the SDK team, I'm going to close this.

Please keep an eye on the changelog in our repo to see if this was added.

Thanks again for your patience,
Ran~
