### ISSUE TITLE
The Synthetics Canary update-canary command doesn't pull updated code from S3

### ISSUE THREAD

**Issue by endre-synnes** [aws/aws-sdk#489]
### Describe the bug

When running the `aws synthetics update-canary` command, It seems that the Canary is updated, since the timestamp changes, but the code/script is not updated.

The code is stored in an S3 bucket, and I can confirm that the S3 bucket does contain my updated script.

### Expected Behavior

1. Running: `aws synthetics update-canary --name <CANARY_NAME> --code '{"S3Bucket": "<S3_BUCKET_NAME>", "S3Key":"<S3_KEY>", "Handler": "<HANDLER_FILE_AND_FUNCTION>", "S3Version": "<S3_OBJECT_VERSION>"}'`

2. Returning: success message.

3. Timestamp for last updated is changed.

4. Canary script successfully updated.

### Current Behavior

1. Running: `aws synthetics update-canary --name <CANARY_NAME> --code '{"S3Bucket": "<S3_BUCKET_NAME>", "S3Key":"<S3_KEY>", "Handler": "<HANDLER_FILE_AND_FUNCTION>", "S3Version": "<S3_OBJECT_VERSION>"}'`

2. Returning: success message

3. Timestamp for last updated is changed.

4. Script not updated.

### Reproduction Steps

1. Create canary and use S3 as data source for the script (I have used the [terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/synthetics_canary) to initially create the Canary.).
2. Verify that the Canary is created and runs successfully.
3. Upload new version of the canary script to the s3 bucket.
4. Run the `aws synthetics update-canary` CLI command to make Canary pull new script: `aws synthetics update-canary --name <CANARY_NAME> --code '{"S3Bucket": "<S3_BUCKET_NAME>", "S3Key":"<S3_KEY>", "Handler": "<HANDLER_FILE_AND_FUNCTION>", "S3Version": "<S3_OBJECT_VERSION>"}'`

### Possible Solution

I'm not sure how to fix this issue, but It would be great to have some form sort of an error message if the update command is actually failing.

### Additional Information/Context

There is no error returned when I execute the command, and if I run it in debug mode, Its not logging any issues.

### CLI version used

2.2.38

### Environment details (OS name and version, etc.)

Mac OS version 13.2.1

**Comment by tim-finnigan** [comment]
P83042349

**Comment by endre-synnes** [comment]
> Thanks for following up and sharing those logs. I could also reproduce the behavior you described. I'm going to transfer this issue to our cross-SDK repository and reach out to the Synthetics team for further review.

Thank you @tim-finnigan!

**Comment by vitalii-shemetov** [comment]
Hello @tim-finnigan 
Are there any updates on that? I'm having the same issue

**Comment by vitalii-shemetov** [comment]
@endre-synnes @tim-finnigan 
I managed to solve the issue by RTFM of AWS CLI command. In my case, there were 2 issues: 
1. Invalid folders structure in canary.zip
2. "S3Bucket" value should be specified without "S3://"

Here is an example of my command line which works for me:
I run it from Windows Cmd:

`update-canary --region us-east-1 --name my_canary --debug --no-verify-ssl --code="{\"S3Bucket\":\"some-autotests-bucket\",\"S3Key\":\"canary.zip\",\"Handler\":\"index.handler\"}" `

I hope it will be useful

**Comment by saulgiordani** [comment]
I have a similar issue: i'm trying to update a canary with a web-identity role-based, i receive a 200 as response but the environment variables are not updated. Same operation with my aws user, it works fine, and the response is basically the same.

The oidc role's policy is

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "cloudwatch:PutMetricData",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "synthetics:*"
            ],
            "Resource": "*"
        }
    ]
}

**Comment by tim-finnigan** [comment]
Thanks all for your patience here. I discussed this issue with a member of the service team, who noted that this behavior is expected because the [UpdateCanary](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_UpdateCanary.html) API is functioning asynchronously. Therefore it is not designed to validate the existence of an S3 key in a customer account. Once the command finishes running, the canary will go in ERROR state. A [get-canary](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/synthetics/get-canary.html) call on it will show the reason for failure, which should look something like this:

```
"Status": {
            "State": "ERROR",
            "StateReason": "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: <>; Proxy: null)",
            "StateReasonCode": "UPDATE_FAILED"
        }
```
I suggested that the documentation be updated to better clarify this behavior. I encourage anyone else who stumbles on this to click the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=CloudWatch&topic_url=https://docs.aws.amazon.com/en_us/AmazonSynthetics/latest/APIReference/API_UpdateCanary.html) button at the bottom of the API documentation page. Any updates to the API documentation will be reflected in the CLI/SDK docs. Thanks again for reporting this issue.
