### ISSUE TITLE
Content-Encoding is blank in S3 Console when `aws-chunked` is passed

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#498]
Original issue: https://github.com/boto/boto3/issues/3629

**Comment by tim-finnigan** [comment]
P83760338

**Comment by BroMattMiller** [comment]
This blank header is breaking my website when I turn on CloudFront compression. The user's web browser ends up getting two Content-Encoding headers, the blank one from S3 and the "br" one added by CloudFront. Firefox is able to deal with this and correctly respects the "br" one, but Chrome and others don't recognize the content as compressed. All I did was use `aws s3 sync ...` to upload these files, which I guess decides to use chunking on some files.

So, just adding this common use case to this bug.

**Comment by tmarcu** [comment]
I see this issue is popping up in various language sdk's, so I'll add my findings here: I am using the `aws-sdk-go-v2` and experiencing the same problem - empty (no value) Content-Encoding header automatically added to my objects even when it is not specified.
Debugging further, this happens specifically when uploading objects that _do not_ need multiple chunks to upload. If I create an object that requires at least 2 chunks (e.g 6MB+), the header is not added anymore. On the go sdk side, this splits off at https://github.com/aws/aws-sdk-go-v2/blob/main/feature/s3/manager/upload.go#L355.

**Comment by ben6reul** [comment]
I'm seeing this issue as well when upgrading from 1.12.157 -> 2.25.47 with the java SDK for small files under the chunking threshold.

**Comment by alex-keeler** [comment]
Are there any updates on a resolution? My team is running into this issue with every file we upload to S3, since we are utilizing the additional checksums feature to add the file's checksum as an object attribute. The empty Content-Encoding is breaking the content on Chrome and Safari when delivered through CloudFront, since both "Content-Encoding: " and "Content-Encoding: br" is present in the response headers. This behavior is affecting our adoption of S3 and CloudFront.

**Comment by BroMattMiller** [comment]
I worked around this for now with a CloudFront Origin Response function. It’s pretty simple to fix the headers there.

**Comment by ima747** [comment]
We just got caught by this as well attempting to enable gzip compression with cloudfront on top of files stored in S3. We are writing out files with Boto3 (python sdk), and after fighting with cloudfront for a while discovered the empty Content-Encoding metadata in S3.

**Comment by flohall** [comment]
+1 from our side.

Deployed the issue yesterday to production, after switching to aws crt client.

AWS Java SDK 2 [2.28.13](https://mvnrepository.com/artifact/software.amazon.awssdk/aws-sdk-java/2.28.13)
AWS CRT [0.31.3](https://mvnrepository.com/artifact/software.amazon.awssdk.crt/aws-crt/0.31.3) 
Java Corretto 21
Spring boot: 3.2.1

Sadly we didn't test this specific scenario before, as we only rarely upload compressable files - we don't have the issue with images for example.
AWS actually recommends people to switch to the client, because it should be more performant - its printed in the logs.

We probably will work around this via cloudfront lambda, which will create additional costs.

Please fix this.

**Comment by jmklix** [comment]
Closing this tracking issue. Please check the original issue for updates: https://github.com/boto/boto3/issues/3629
