### ISSUE TITLE
kafka get-bootstrap-brokers doesn't return all brokers

### ISSUE THREAD

**Issue by karankand** [aws/aws-sdk#500]
### Describe the bug

kafka get-bootstrap-brokers doesn't return all brokers. Itried executing couple of time , every time only any 3 brokers will be returned.

### Expected Behavior

Should return all brokers in cluster.

### Current Behavior

 only any 3 brokers will be returned.

### Reproduction Steps

Cluster with more than 3 brokers.
aws kafka get-bootstrap-brokers --cluster-arn  arn:aws:kafka:**:**:cluster/***** 
Brokers per zone - 2
Total number of brokers - 4

### CLI version used

aws-cli/2.11.2

### Environment details (OS name and version, etc.)

macOs Monterey 12.6.3

**Comment by tim-finnigan** [comment]
P84110006

**Comment by tim-finnigan** [comment]
Hi @eduardoasantana I haven't heard back from the Kafka team regarding the documentation issue yet. I'm not aware of any updates made to the API — you can check the CHANGELOG of whichever SDK you're using to see changes in functionality by version. But I think the API returning 3 brokers is expected behavior based on this documentation: https://docs.aws.amazon.com/msk/latest/developerguide/msk-get-bootstrap-brokers.html.

>The bootstrap brokers string should contain three brokers from across the Availability Zones in which your MSK cluster is deployed (unless only two brokers are available). 

I can't speak to the design of the API as I don't have context on that, but hoping the Kafka documentation writes can provide more insight.

**Comment by jayteej** [comment]
Hello, I think there has been some confusion. The `get-bootstrap-brokers` api only returns 3 brokers by design. Specifically these brokers are a random selection of 3 for "bootstrapping". 

The Kafka producer and consumer clients will discover other brokers in the cluster by making a getMetadata request to one of the bootstrap brokers. This metadata is periodically updated by the client and also updated in failure cases if a broker goes offline.

The only reason for having 3 is having redundancy when performing initial discovery.
