### ISSUE TITLE
[EC2][createFleet] The option to add the UserData in base64 in the createFleet action is missing

### ISSUE THREAD

**Issue by Myky8** [aws/aws-sdk#528]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm migrating the requestSpotFleet method to createFleet, as recommended by amazon, due to requestSpotFleet being discontinued. "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html#which-spot-request-method-to-use"

The problem is that there is currently no way to add the UserData in the creation of the fleet with this method, I understand that it should be located in the Overrides section of the LaunchTemplate: FleetLaunchTemplateOverridesRequest.

This UserData is what is used to pass information to the machines that the fleet starts and that can be requested from the machine through a request to an internal url. "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-add-user-data.html"

On the other hand, in the old requestSpotFleet method, this UserData existed precisely in SpotFleetLaunchSpecification, and even in the LaunchTemplate from the console it can be added, but when you need to add dynamic information directly from the command, with createFleet it is not possible.

There is another attribute that allows you to configure requestSpotFleet, but not createFleet, which consists of adding Tags to the instances created by the fleet.

### SDK version number

@aws-sdk/client-ec2@3.198.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.18.0

### Reproduction Steps

Check in the input of the createFleet command, the option to add the UserData does not appear.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/createfleetcommandinput.html

### Observed Behavior

Check in the input of the createFleet command, the option to add the UserData does not appear.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/createfleetcommandinput.html

### Expected Behavior

Enabling UserData can override the LaunchTemplate's in the createFleet action.

**Comment by RanVaknin** [comment]
Hi @Myky8 ,

I've heard back from the EC2 service team:

This is the expected behavior. Following are the ways to add UserData and instance tags.

>The problem is that there is currently no way to add the UserData in the creation of the fleet with this method, I understand that it should be located in the Overrides section of the LaunchTemplate: FleetLaunchTemplateOverridesRequest.

We do not allow UserData to be overridden in the launch template overrides. Customers can set this while creating a launch template: https://docs.aws.amazon.com/cli/latest/reference/ec2/create-launch-template.html. Fleet will use the userData specified in the launch template: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/manage-ec2-fleet.html#ec2-fleet-prerequisites-launch-template. We don't have any workarounds as of now to add user data apart from adding it in launch template, will evaluate this request for our roadmap this year

>There is another attribute that allows you to configure requestSpotFleet, but not createFleet, which consists of adding Tags to the instances created by the fleet.

To tag instances and volumes when they are launched by the fleet, specify the tags in the launch template that is referenced in the EC2 Fleet request. : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/manage-ec2-fleet.html#tag-ec2-fleet

We apologize for the inconvenience and hope that the steps described here by the service team can be helpful. 
It sounds like your concerns got translated into a feature request. 
At this time I'm not able to provide you with additional details / solutions so I'm going to close this issue.

If you have any additional questions please feel free to open a new issue.

Thanks,
Ran~
