### ISSUE TITLE
SDK does not expose Bookmarks feature for Quicksight Embed URL request

### ISSUE THREAD

**Issue by OneHoopyFrood** [aws/aws-sdk#545]
### Describe the bug

According to this: https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-quicksight-state-persistence-bookmarks-embedded-dashboards/
And this: https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GenerateEmbedUrlForRegisteredUser.html

The request can now contain `Bookmarks: {Enabled: true}`.

I would expect the SDK to expose this as `BookmarksEnabled` but it's not on the type and thus can't be passed through.

### Expected Behavior

The SDK should expose a `BookmarksEnabled` flag for Quicksight GetDashboardEmbedUrlRequest

https://github.com/aws/aws-sdk-js/blob/372fd421704c8b5dbb68a15b5cefdbe7850dce56/clients/quicksight.d.ts#L9225

### Current Behavior

Does not expose this feature. 

### Reproduction Steps

N/A Sdk simply does not expose this functionality though the types.

### Possible Solution

Add this to the types and make necessary supporting code changes to ensure the request body contains the correct value.

### SDK version used

2.1390.0 (latest)

### Environment details (OS name and version, etc.)

MacOS 13.1

**Comment by OneHoopyFrood** [comment]
Thank you!

**Comment by RanVaknin** [comment]
Hi @OneHoopyFrood ,

I misunderstood your request.  I thought you mentioned `GenerateEmbedUrlForRegisteredUser` did not include the correct field even though they were documented. From looking at the model it is available.

`GetDashboardEmbedUrlRequest` does not offer Bookmarks as a param on the API level, so the SDK cannot "expose" it. Like I mentioned before, the SDKs are code generated from the API model, if the service model lacks a field, the SDK team cannot add it (indicating it doesnt have service side support) 
From speaking to the quicksight service team: "GetDashboardEmbedUrlRequest  Its an outdated API and the Quicksight service does not release new features for it:
>"We do not plan to add Bookmarks to `GetDashboardEmbedUrlRequest`  as that is an outdated API. As customer has called out the only way to use this feature is via the `GenerateEmbedUrlForRegisteredUser` API."


Since there is no actionable item for the SDK team, I feel confident we can close this. 
Thanks,
Ran~

**Comment by OneHoopyFrood** [comment]
I see. I would recommend an update to the documentation and js-doc header to indicate this is deprecated unless I missed this somewhere?

**Comment by OneHoopyFrood** [comment]
Ah! I do see there is a notice here: https://docs.aws.amazon.com/quicksight/latest/user/embedding-dashboards.html
I just didn't come across that before. I still recommend adding the @deprecated tag to the js-docs.
