### ISSUE TITLE
Wrong Default timeoutInMins of buildBatchConfig 

### ISSUE THREAD

**Issue by digglife** [aws/aws-sdk#624]
According to the AWS Console, the valid range of `timeoutInMins` of `buildBatchConfig` for CodeBuild project is `5-480` minutes. But if I set the `buildBatchConfig` with `serviceRole`, which is the only required field, the `timeoutInMins` will be set as `2160` by default.

### How to Reproduce

1. Create a CodeBuild Project, without configuring batch build.
2. Set `buildBatchConfig` with `serviceRole` field only via API (SDK in any language).
4. Get the project and you will see the `timeoutInMins` is `2160`.

### Expected Behavior

Defaults to `480`, which is indicated in AWS Console and validated by myself.

<img width="791" alt="image" src="https://github.com/aws/aws-sdk/assets/1468378/7ed6319a-b1f2-4d6a-a629-a79ba0a05ec6">

### Documentation 

In the [API reference](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectBuildBatchConfig.html),`serviceRole` is NOT required, which should be corrected to YES. 

<img width="487" alt="image" src="https://github.com/aws/aws-sdk/assets/1468378/2224b370-7e8e-42cd-85b4-a16092eaf329">

**Comment by tim-finnigan** [comment]
Checking in — the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=CodeBuild&topic_url=https://docs.aws.amazon.com/en_us/codebuild/latest/APIReference/API_ProjectBuildBatchConfig.html) links at the bottom of API reference pages are the best way to send feedback directly to the appropriate team. It looks like there are a couple issues here with the documentation, can you provide a code snippet to reproduce this so that we can verify on our end?

**Comment by digglife** [comment]
Reproduce code snippet. Please replace the value of serviceRole with an actual role.

```
import boto3
codebuild = boto3.client('codebuild')

# replace the value of serviceRole with an actual role
codebuild.create_project(name="batchconfig_issue_reproduce", source={"type":"GITHUB", "location":"https://github.com/aws/aws-sdk"}, environment={'type': 'LINUX_CONTAINER','image': 'aws/codebuild/amazonlinux2-x86_64-standard:4.0', 'computeType': 'BUILD_GENERAL1_SMALL'}, serviceRole='arn:aws:iam::694766239021:role/CodeBuildBaseRole', artifacts={'type': 'NO_ARTIFACTS'})

# replace the value of serviceRole with an actual role
res = codebuild.update_project(name="batchconfig_issue_reproduce", buildBatchConfig={"serviceRole":'arn:aws:iam::694766239021:role/CodeBuildBaseRole'})

# check the timeoutInMins, it's 2160 but supposed to be 480
print(res['project']['buildBatchConfig'])
```

For the documentation I've submitted feedback. Thanks for advising.

**Comment by digglife** [comment]
@tim-finnigan 
Here is the reproduce code snippet. Please replace the value of `serviceRole` with an actual role.

```
import boto3
codebuild = boto3.client('codebuild')

# replace the value of serviceRole with an actual role
codebuild.create_project(name="batchconfig_issue_reproduce", source={"type":"GITHUB", "location":"https://github.com/aws/aws-sdk"}, environment={'type': 'LINUX_CONTAINER','image': 'aws/codebuild/amazonlinux2-x86_64-standard:4.0', 'computeType': 'BUILD_GENERAL1_SMALL'}, serviceRole='arn:aws:iam::694766239021:role/CodeBuildBaseRole', artifacts={'type': 'NO_ARTIFACTS'})

# replace the value of serviceRole with an actual role
res = codebuild.update_project(name="batchconfig_issue_reproduce", buildBatchConfig={"serviceRole":'arn:aws:iam::694766239021:role/CodeBuildBaseRole'})

# check the timeoutInMins, it's 2160 but supposed to be 480
print(res['project']['buildBatchConfig'])
```

For the documentation I've submitted feedback. Thanks for advising.

**Comment by bhoradc** [comment]
Hi @digglife, 

Thank you for providing more details on this issue. If we don't provide a `timeoutInMins` on the `ProjectBuildBatchConfig`, by default it sets the value to `2160`. This actually matches the API documentation and actual validation on console (for an invalid input). 

**API reference**- [CreateProject](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateProject.html)

![image](https://github.com/user-attachments/assets/ca1b04a3-5b57-46db-bbbd-0865f936bfd5)

**Console screenshot**:

<img width="777" alt="image" src="https://github.com/user-attachments/assets/23656dab-229b-4e53-88a8-0080f41f9175">

The issue seems to be in the console for Batch timeout which is showing incorrect validation text. 

I will create an internal Ticket to the service team to confirm with our findings and to provide a fix. Feel free to add if you think otherwise on the above observation. 

Regards, 
Chaitanya

**Comment by bhoradc** [comment]
V1470519939

**Comment by bhoradc** [comment]
Hi @digglife, 

Service team has updated the correct `BuildBatch` config description on the console. The validation text and the description now matches for the `Batch timeout` max limit.

![image](https://github.com/user-attachments/assets/40ea05a6-21ad-4c80-af71-06c0448b9f44)

I will mark this as `closing-soon` as the requested changes have been completed. 

Regards, 
Chaitanya
