### ISSUE TITLE
The InitiateMultipartUploadInput input partSize is required

### ISSUE THREAD

**Issue by candouss** [aws/aws-sdk#634]
### Describe the issue

Just tried to call the InitiateMultipartUploadCommand without the property 'partSize' and got an exception saying it is mandatory, which does not reflect the documentation. 

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/glacier/command/InitiateMultipartUploadCommand/

**Comment by aBurmeseDev** [comment]
Since we have not received any updates regarding this issue from the service team, and this repository is specifically for SDK-related issues, I will proceed to close this issue. However, you are welcome to directly contact the AWS Support team at [AWS Support](https://aws.amazon.com/contact-us/) for further updates.
