### ISSUE TITLE
GovCloud CLI InvalidToken Error

### ISSUE THREAD

**Issue by CGick** [aws/aws-sdk#647]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When attempting to run `aws s3 ls` on EC2 instance in `us-gov-west-1`, I recieved the following error 
```
aws s3 ls 

An error occurred (InvalidToken) when calling the ListBuckets operation: The provided token is malformed or otherwise invalid.
```

After doing some troubleshooting I discovered that the `--region us-gov-west-1` parameter fixed this error message.

**SDK version number**
```
aws --version
aws-cli/1.16.300 Python/2.7.16 Linux/4.14.171-136.231.amzn2.x86_64 botocore/1.13.36
```
**Platform/OS/Hardware/Device**
EC2 Amazon Linux2 instance

**To Reproduce (observed behavior)**
On an EC2 instance in the AWS GovCloud run the command `aws s3 ls`

**Expected behavior**
This error should be handled more clearly with a message that suggests using the region parameter.

**Comment by tim-finnigan** [comment]
Hello and thanks again for your patience. We heard back from a member of the S3 service team who described that this behavior is due to making API calls between partitions. There is no way within the mechanisms of SigV4 that S3 or other services can know the request would've been valid had you sent it to a different partition's endpoint (nor what partition it would've been valid in), because partitions are completely isolated from each other by design. 

Partitions are described in more detail here: https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/partitions.html

>AWS groups Regions into [partitions](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html). Every Region is in exactly one partition, and each partition has one or more Regions. Partitions have independent instances of AWS Identity and Access Management (IAM) and provide a hard boundary between Regions in different partitions. AWS commercial Regions are in the aws partition, Regions in China are in the aws-cn partition, and AWS GovCloud Regions are in the aws-us-gov partition. Some AWS services are designed to provide cross-Region functionality, such as [Amazon S3 Cross-Region Replication](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html#crr-scenario) or [AWS Transit Gateway Inter-Region peering](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html). These types of capabilities are only supported between Regions in the same partition. You cannot use IAM credentials from one partition to interact with resources in a different partition.

---

And this behavior is not limited to S3 — here are a few examples of other services:

![image](https://github.com/aws/aws-sdk/assets/87778557/4d877769-4150-4b7c-a03d-3364bf679dec)

So the GovCloud issue is not specific to any service, CLI, or SDK. It is due to the inherent limitation of sending requests to an endpoint in another partition. Since this issue affects multiple SDKs, I created a new feature request for adding a clearer error message when making cross-partition requests: https://github.com/aws/aws-sdk/issues/648. This would need to be implemented across AWS SDKs for consistency.
