### ISSUE TITLE
"aws {rds,docdb} describe-db-engine-versions" showing the wrong returns

### ISSUE THREAD

**Issue by guessi** [aws/aws-sdk#718]
### Describe the bug

* Result of `aws rds describe-db-engine-versions` should not contains result for `Amazon DocumentDB`.
* Result of `aws docdb describe-db-engine-versions` should not contains result for `Amazon RDS`.
* Command below should not work
    * `aws docdb describe-db-engine-versions --engine aurora-mysql` ---> mixing results for DocDB and RDS altogether.
    * `aws rds describe-db-engine-versions --engine docdb` ---> mixing results for RDS and DocDB altogether.

### Expected Behavior

* Command for Product A should not returns result for Product B.

### Current Behavior

Commands below showing the same result

```
$ aws rds describe-db-engine-versions --output json | jq -r '[.DBEngineVersions[].Engine] | sort | unique'
[
  "aurora-mysql",
  "aurora-postgresql",
  "custom-sqlserver-ee",
  "custom-sqlserver-se",
  "custom-sqlserver-web",
  "db2-ae",
  "db2-se",
  "docdb",
  "mariadb",
  "mysql",
  "neptune",
  "postgres",
  "sqlserver-ee",
  "sqlserver-ex",
  "sqlserver-se",
  "sqlserver-web"
]
```

```
$ aws docdb describe-db-engine-versions --output json | jq -r '[.DBEngineVersions[].Engine] | sort | unique'
[
  "aurora-mysql",
  "aurora-postgresql",
  "custom-sqlserver-ee",
  "custom-sqlserver-se",
  "custom-sqlserver-web",
  "db2-ae",
  "db2-se",
  "docdb",
  "mariadb",
  "mysql",
  "neptune",
  "postgres",
  "sqlserver-ee",
  "sqlserver-ex",
  "sqlserver-se",
  "sqlserver-web"
]
```
### Reproduction Steps

Just execute the commands provided.

### CLI version used

* `latest (aws-cli/2.15.36 Python/3.11.9 Darwin/23.4.0 source/x86_64 prompt/off)`

### Environment details (OS name and version, etc.)

* `see above info`

**Comment by tim-finnigan** [comment]
Thanks for your patience. We heard back form the service teams who noted that this is the expected behavior. From the RDS side, they noted that DocDB is an RDS engine, so from that perspective this works as intended. And for DocDB, to view the engine versions for a specified engine you can use the `--engine` parameter:
```
aws docdb describe-db-engine-versions \
    --engine docdb
```
If you believe the documentation could better clarify this behavior, please feel free to reach out via the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=DocumentDB&topic_url=https://docs.aws.amazon.com/en_us/documentdb/latest/developerguide/API_DescribeDBEngineVersions.html) links in the API documentation pages to connect with the appropriate team. Any updates to the API documentation will be reflected in the CLI/SDK documentation.
