### ISSUE TITLE
No Option to filter attributes based on Regex Match in Cognito

### ISSUE THREAD

**Issue by zubairzahoor** [aws/aws-sdk#725]
I need to get a list of emails that end with a particular domain(s) from Cognito by using cognito.listUsers({}).
Right now I can only either provide the filter type for an exact match using = or for a prefix match using ^= which is extremely limited to say the least. 
I (along with possibly many other developers) would like to have the ability to list users from cognito based on a match with a regex pattern. 
Or have a options like 'contains', 'not contains', 'ends with', 'exists' and more like these to be able to list the users we  exactly want.

Right now, I have to retrieve each and every user in Cognito User Pool using Pagination and then filter them based on what I need which of course is no good when the total number of Users goes in thousands (given there is a limit of 60 users per page and a rate limit on number of requests)

**Comment by RanVaknin** [comment]
Hello everyone on this thread. 

Thank you for your patience. We had to dig this issue up from the old JS SDK v2 repo that is now is officially in maintenance mode. We apologize for not seeing this sooner. We now have better tools that help detect languishing issues of this sort, so hopefully we can minimize these sorts of scenarios where issues get unnoticed going forward.

To be clear, this feature request is intended for the Cognito service itself, and not the SDK team. The ask to add regex based service-side filtering is an API enhancement. Since the AWS SDKs are code generated from the API of the various AWS services, the SDK team cannot add this filtering functionality, especially because this needs to be supported with upstream with the service itself first.

I have upstreamed this feature request to the Cognito team directly (internal ticket `#P145422926`). Our team does not have visibility as to when / if this is going to be implemented, all we can do is advocate on your behalf and make sure this is seen by the right people. 

If any of the 36+ participants on this thread has access to AWS support via the AWS console, I highly encourage you to open a support ticket and reference the ticket ID mentioned above. 

Since this is not directly actionable by the SDK team, once we hear back from the service team I will provide an update and close this issue. 

Thanks again for all of the engagement,
Ran~
