### ISSUE TITLE
Add custom headers support to SES sendBulkTemplatedEmail

### ISSUE THREAD

**Issue by chrisc0** [aws/aws-sdk#793]
### Describe the feature

I need to be able to add custom email headers while sending out hundreds (potentially thousands) of emails at a time using the SES sendBulkTemplatedEmail command but it doesn't currently seem possible.

### Use Case

I need to be able to add custom email headers while sending out hundreds (potentially thousands) of emails at a time using the SES sendBulkTemplatedEmail command but it doesn't currently seem possible.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8.1.2, Ubuntu 22.04

**Comment by yenfryherrerafeliz** [comment]
Internal ticket: V1467804965

**Comment by yenfryherrerafeliz** [comment]
Hi @chrisc0, @nicodemuz, @DevKishan, @HashimHaider, @gileri, @kaaaaaaaaaaai, @serbanveres, @TomWaterz, sorry for the delay on answering here. Since this is a limitation from the service itself there is nothing we can do from an SDK perspective, however, I have opened a ticket with them and I have forward your pain points and why this is needed based on your sentiments. 

I will be awaiting a response from the service and I will make sure to place further updates here.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @chrisc0, @nicodemuz, @DevKishan, @HashimHaider, @gileri, @kaaaaaaaaaaai, @serbanveres, @TomWaterz!

I just got back from the service and it looks like this functionality is already present in the V2 API of SES. Please use the `SESV2Client` instead of `SESClient` and you should be able to provide custom headers.

Here is the doc: https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html

Please let me know if that helps or if you have any comments or questions. 

Thanks.

**Comment by boehs** [comment]
I'm calling https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html#API_SendBulkEmail_RequestSyntax,  to it I passed the following: ```
{
"FromEmailAddress": "\"xxx Notifications\" <mailer@xxx.org>",
"DefaultContent": {
  "Template": {
    "TemplateName": "xxx",
  }
},
"BulkEmailEntries": [
  {
    "Destination": {
      "ToAddresses": [
        "<email>"
      ]
    },
    "ReplacementEmailContent": {
      "RepacementTemplate": {
        "ReplacementTemplateData": "{\"uuid\":\"939e7050936b4e41b8be5ac2752d1b74\"}"
      }
    },
    "ReplacementHeaders": [
      {
        "Name": "List-Unsubscribe",
        "Value": "<https://xxx.org/api/unsubscribe/939e7050936b4e41b8be5ac2752d1b74>"
      },
      {
        "Name": "List-Unsubscribe-Post",
        "Value": "List-Unsubscribe=One-Click"
      }
    ]
  }
]
}
``` however, I was getting template rendering errors, so I tried ```
DefaultContent: {
  Template: {
    TemplateName: template,
    TemplateData: JSON.stringify({
      uuid: "0",
    }),
  },
},
```
And this fixed the render errors, but UUID was set to "0" in the emails that were sent.

I've checked about a million times to ensure I'm following the docs and it all looks good,  but it just won't work. The only other complaint I could find was [here](https://repost.aws/questions/QUWqMQAZJ3Q9msQatESfb5qA/custom-headers-support-in-ses-sendbulktemplatedemail-command#AN8_Qy7cbnSqCurNsPbSVT4Q) and its unresolved.

Any ideas?

**Comment by ashishdhingra** [comment]
@boehs Per [TemplateData](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_Template.html#SES-Type-Template-TemplateData), it is `An object that defines the values to use for message variables in the template. This object is a set of key-value pairs. Each key defines a message variable in the template. The corresponding value defines the value to use for that variable.`. It replaces the message variable in template, not the headers.

You could try using [ReplacementHeaders](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_BulkEmailEntry.html#SES-Type-BulkEmailEntry-ReplacementHeaders) for your scenario to replace headers in the individual `BulkEmailEntry` objects.

Thanks,
Ashish

**Comment by boehs** [comment]
@ashishdhingra I'm not trying to replace headers, well I'm trying to do that too, but I believe there's a bug in this API where `ReplacementTemplateData` *does not* work. See the re:post thread I [linked](https://repost.aws/questions/QUWqMQAZJ3Q9msQatESfb5qA/custom-headers-support-in-ses-sendbulktemplatedemail-command#AN8_Qy7cbnSqCurNsPbSVT4Q) above.

**Comment by tim-finnigan** [comment]
Thanks all for your patience. As mentioned [here](https://github.com/aws/aws-sdk/issues/793#issuecomment-2286796848) earlier, the recommendation from the service team was to use the SESV2Client instead of SESClient and you should be able to provide custom headers. Here is the doc: https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html. There are not plans to support this on v1 of the API.

**Comment by boehs** [comment]
@tim-finnigan nobody ever responded to the issue I raised above with the V2 client?
