### ISSUE TITLE
Support `DescribeExection` for Express Step Functions

### ISSUE THREAD

**Issue by Elevating7734** [aws/aws-sdk#796]
### Describe the feature

The CLI should support polling an execution for status

### Use Case

An express step function can be triggered via the CLI, but the status cannot be checked. This reduces confidence in the solution, as I need the ability to poll whether the execution has been completed or failed.

Ex:
```
> aws stepfunctions start-execution --state-machine-arn <REDACTED>
{
    "executionArn": "<REDACTED>",
    "startDate": "2024-07-18T11:44:22.561000-07:00"
}

```

### Proposed Solution

Add CLI and/or API functionality to poll an express state machine for the status.

Ex: `aws stepfunctions get-execution-history --execution-arn <ARN>`

### Other Information

Duplicates older issue, raised by another user and closed for inactivity https://github.com/aws/aws-cli/issues/7476

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.17.13 Python/3.11.9 Windows/10 exe/AMD64

### Environment details (OS name and version, etc.)

Microsoft Windows 11 Pro / 10.0.22631 Build 22631

**Comment by tim-finnigan** [comment]
We heard back from the Step Functions team, who noted that express state machine execution history is not recorded in Step Functions by design — they rely on CloudWatch logs and customers should be able to retrieve them from the CloudWatch group.

If you enable CloudWatch config in the state machine, you can pull the execution status with the CloudWatch [FilterLogEvents API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html).

You can refer to the documentation here for the difference between standard and execution:
https://docs.aws.amazon.com/step-functions/latest/dg/diff-standard-express-exec-details-ui.html

So the service team does not plan to change this behavior, but if you'd like me to forward any additional information regarding your use case to them please let me know.
