### ISSUE TITLE
Add waiters for Athena

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#80]
Originally requested at boto/boto3#1212, [botocore PR #1358](https://github.com/boto/botocore/pull/1358) and [botocore PR #1868](https://github.com/boto/botocore/pull/1868)

**Comment by stobrien89** [comment]
P47956927

**Comment by stobrien89** [comment]
Hi all,

No updates from the Athena team just yet, but I just reached out to request one.  I'll let you know as soon as I have more info!

**Comment by djbpark1** [comment]
Hi, the [latest docs for boto3 Athena Client](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html#Athena.Client.get_waiter) has a `get_waiter()` method. Is it still not implemented?

**Comment by dylanpancoast** [comment]
Hi guys. I see no waiters section [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html), should we consider this feature to not be implemented?

**Comment by tim-finnigan** [comment]
The service team is still tracking this feature request but it has not yet been prioritized. The `get_waiter()` method is documented across Boto3 clients but does not mean that waiters are available for each client.

**Comment by adityamatt** [comment]
Bumping this again to know the status of the issue

**Comment by jmklix** [comment]
I reached out to the Athena team and shared your use case to gather more insights on your behalf. Since this issue isn’t directly actionable by the SDK team, and this repository is dedicated to SDK-related issues, I'll go ahead and close this ticket. If you have access to AWS support through the Developer Console, please consider creating a support ticket and referencing the ticket ID I shared above to receive updates directly from the service team. Otherwise, you can keep an eye on our release notes for news on when this is resolved.
