### ISSUE TITLE
Does the RDSDataService support array parameters?

### ISSUE THREAD

**Issue by arcturial** [aws/aws-sdk#9]
Confirm by changing [ ] to [x] below:
- [ x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I am encountering an error when trying to use the "arrayValue" parameter for the RDSDataService, it results in the "Array parameters are not supported." error.

My request looks like this
```
{
  query: xxx
  continueAfterTimeout:false,
  includeResultMetadata:true,
  parameters: [
    { name: company_id, value: { arrayValue: { longValues: [11] } } }
  ]
}
```

This is how the documentation seems to format the packet, am I doing something wrong?

**Comment by vic-blt** [comment]
This is a big issue for me because I need to execute a `SELECT` for several IDs and, as I can't use the `IN` keyword, I have to move the `SELECT` into a loop.
Instead of one request with an array of IDs, I have to make a request for each ID which is counter performant, especially if you have a lot of IDs to `SELECT`.
BTW, I tried to join the IDs with `ids.join("','")` and pass it as a `stringValue` parameter but quotes are escaped to prevent SQL injection, so I can't use this tweak.

**Comment by silviuglv** [comment]
Ran into this issue as well, my workaround was to create the array as a string and cast it.

```
   {
        name: 'colum',
        value: `{'${myArray.join(',')}'}`,
        cast: 'text[]',
   }
```

**Comment by webjema** [comment]
Hey!
Do you have any ETA when the service team is going to release arrays support?

**Comment by jannikmi** [comment]
> Ran into this issue as well, my workaround was to create the array as a string and cast it.
> 
> ```
>    {
>         name: 'colum',
>         value: `{${myArray.join(',')}}`,
>         cast: 'text[]',
>    }
> ```

I could not create any successful workaround with the code snippet you gave.
Could you please be more specific?

Additional search pointed me to this more explicit example: https://github.com/koxudaxi/local-data-api#how-to-insert-array-data-into-postgresql
They point out to put casting into the SQL command like 
```
[...] cast(:parameter_name as text[]) [...]
```

In my case however that did not work.
I am trying to query for a list of certain ids like this:

```
SELECT ('id') FROM "table_name" WHERE "id" NOT IN cast(:allowed_ids as int[])
```

with paramters looking like:

```
[{'name': 'allowed_ids', 'value': {'stringValue': "{4,1}"}}]
```

That gives me:

```
[ERROR] BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: ERROR: syntax error at or near "cast"
  Position: 145
```

BTW: `"SELECT cast('{4,1}' as int[])"` works fine.
Is the error due to escaping as it has been pointed out here:

> BTW, I tried to join the IDs with ids.join("','") and pass it as a stringValue parameter but quotes are escaped to prevent SQL injection, so I can't use this tweak.

**Comment by silviuglv** [comment]
I'm not the best person to answer this as I'm not that proficient in SQL but I believe the issue is that when you do `SELECT cast('{4,1}' as int[])` you're basically querying a list of ids `{}` but `SeLECT .... WHERE id IN` is a function `()` that is why you're getting an error.

Have you tried with:
query: `SELECT ('id') FROM "table_name" WHERE "id" NOT IN :allowed_ids` 
params: [{'name': 'allowed_ids', 'value': `(${ids.join(',')})`]

I think this needs a bit of trial and error but the main point is that after `IN` you should have a list of params like `('id1', 'id2')` not a SQL type array `{id1, id2}` which the casting is giving you.

Hope this helps :)

**Comment by jannikmi** [comment]
Thanks for the idea. Unfortunately I get the same error with:
```
SELECT ('id') FROM "table_name" WHERE "id" NOT IN :allowed_ids
```
```
parameters = [{'name': 'allowed_ids', 'value': {'stringValue': "(4,1)"}}]
```
And it is also understandable that `SELECT ('id') FROM "table_name" WHERE "id" NOT IN  "(4,1)"` also is not valid SQL.
But passing a list (or tuple) as value is not possible, which is the reason for this issue in the first place.

**Comment by ajredniwja** [comment]
Reached out to the RDS team again for them to work on it but I am not sure about the priority of it. 
V397315224

**Comment by dhruvsense** [comment]
Bump, it seems like a basic functionality, it does make the use of DataAPI pointless if it cannot support the core datatypes of the database. Please take this up!

**Comment by natech3ng** [comment]
thumbsup, it's a relatively an important and basic function.

**Comment by rakesh-saiga** [comment]
is this feature to use Array parameters is possible anytime near soon? this would be super helpful if available

**Comment by frankisans** [comment]
Base on @sambs workaround:
```
const parameters = ids.map((id, index) => ({ name: `id${index}`, value: {stringValue: id} }))
const placeholder = [...Array(ids.length).keys()].map(x => `:id${x}`).join(',')
const params = {
    secretArn: 'yourSecretArn',
    resourceArn: 'yourResourceArn',
    sql: `SELECT * FROM member WHERE member_id IN (${placeholder})`,
    parameters 
  })
```

**Comment by rakesh-saiga** [comment]
Hello @frankisans  I did try this option but i see same error `An error occurred (BadRequestException) when calling the ExecuteStatement operation: Array parameters are not supported.` it would be super helpful to have this feature if supported by default rather than attempting to find workarounds :)

**Comment by frankisans** [comment]
Hi @rakesh-saiga I use this solution with @aws-sdk/client-rds-data v3.72 with lambda function and is working fine.

**Comment by rakesh-saiga** [comment]
i see, in my case error was when using go library of rds-data package. hence may be the issue we are seeing are different

**Comment by lefnire** [comment]
@frankisans workaround works for me. Pretty bonkers this isn't supported, what does `arrayValue` from [docs](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html) do then? Is it a placeholder for future functionality?

**Comment by jlag34** [comment]
@sambs @frankisans thank you so much for this. After hours of dead ends, I finally got it to work with your solutions

**Comment by lefnire** [comment]
Here's a bit of a shim per @frankisans fix https://gist.github.com/lefnire/26d72911ee7fb7dcf82fc5d919d192a5

**Comment by ashishdhingra** [comment]
Backlog item in queue in the service team backlog. As of now, we can't share specific timelines on when this might be implemented in GitHub. Reached out to service team for the update.

Closing this issue since it is tracked in the service team's backlog. The feature, once supported by service team, should be available to all SDK(s) automatically, with API documentation updated.
